# Vivado batch programming entry.
# Default behavior: auto-pick latest bit generated by build flow and program first detected device.
# Usage:
#   vivado -mode batch -source fpga_side/scripts/vivado/program_device.tcl
#   vivado -mode batch -source fpga_side/scripts/vivado/program_device.tcl -tclargs <bit_file>

set bit_file ""
if {$argc >= 1} {
  set bit_file [lindex $argv 0]
}

if {$bit_file eq ""} {
  set default_bits [glob -nocomplain ./fpga_side/rtl/build/*/*.runs/impl_1/*.bit]
  if {[llength $default_bits] == 0} {
    puts "ERROR: no bitstream found under fpga_side/rtl/build/*/*.runs/impl_1"
    puts "HINT: run build_bit.tcl first"
    exit 2
  }

  set latest_mtime 0
  set latest_bit ""
  foreach f $default_bits {
    set m [file mtime $f]
    if {$m > $latest_mtime} {
      set latest_mtime $m
      set latest_bit $f
    }
  }
  set bit_file $latest_bit
}

if {![file exists $bit_file]} {
  puts "ERROR: bitstream not found: $bit_file"
  exit 3
}

# Vivado 2019.1 compatible hardware manager API
open_hw
connect_hw_server
open_hw_target

set hw_devices [get_hw_devices]
if {[llength $hw_devices] == 0} {
  puts "ERROR: no hardware devices detected"
  close_hw
  exit 4
}

set dev [lindex $hw_devices 0]
refresh_hw_device $dev

set_property PROGRAM.FILE $bit_file $dev
program_hw_devices $dev
refresh_hw_device $dev

puts "PROGRAM DONE"
puts "DEVICE: $dev"
puts "BIT: $bit_file"

close_hw_target
close_hw
